config/routes.rb
Rails.application.routes.draw do

  root 'tasks#index'

  get 'menu' => 'access#menu'
  get 'login' => 'access#new'
  delete 'logout' => 'access#destroy'
  resource :access, controller: 'access', only: [:new, :create, :destroy] do
    member do
      get :menu
    end
  end

  match 'about', to: 'main#about', via: :get

  resources :categories do
    member do
      get :delete
    end
  end

  resources :tasks do
    member do
      get :delete
    end
  end

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/category.rb
class Category < ApplicationRecord
    has_many :tasks
end

app/models/task.rb
class Task < ApplicationRecord
    belongs_to :category, optional: true
end

app/controllers/access_controller.rb
class AccessController < ApplicationController
   # display menu
  def menu
    @username = cookies[:username]
  end

  # display login form
  def new
  end

  # processs login form
  def create
    # do login process here
    cookies[:username] = params[:username]
    redirect_to(menu_path)
  end

  # logout user
  def destroy
    # do logout process here
    redirect_to(login_path)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def index
    @categories = Category.all
  end

  def show
    @category = Category.find(params[:id])
  end

  def new
  end

  def create
  end

  def edit
  end

  def update
  end

  def delete
  end

  def destroy
  end
end

app/controllers/main_controller.rb
class MainController < ApplicationController
  def index
  end

  def about
    @created_by = "Julia"
    @id = params['id']
    @page = params[:page]
  end

  def hello
    redirect_to(action: 'index')
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  def index
    @tasks = Task.order(:position)
  end

  def show
    @task = Task.find(params[:id])
  end

  def new
    @count = Task.count
    @task = Task.new(position: @count + 1)
  end

  def create
    @task = Task.new(task_params)
    if @task.save
      redirect_to tasks_path
    else
      # The 'new' action is NOT being called here
      # Assign any instance variables needed
      # @count = Task.count
      render('new')
    end
  end

  def edit
    @task = Task.find(params[:id])
  end

  def update
    @task = Task.find(params[:id])
    if @task.update(task_params)
      redirect_to task_path(@task)
    else
      render('edit')
    end
  end

  def delete
    @task = Task.find(params[:id])
  end

  def destroy
    @task = Task.find(params[:id])
    @task.destroy
    redirect_to tasks_path
  end

  private

  def task_params
    params.require(:task).permit(
      :name,
      :position,
      :completed,
      :description
    )
  end

end

app/helpers/access_helper.rb
module AccessHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/main_helper.rb
module MainHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/access/menu.html.erb
<div class="access index">
  <h1>Menu</h1>

  <p>User: <%= @username %></p>

  <ul>
    <li><%= link_to('Manage Tasks', tasks_path) %></li>
    <li><%= link_to('Manage Categories', categories_path) %></li>
    <li><%= link_to('About', {controller: 'main', action: 'about'}) %></li>
  </ul>

</div>

app/views/access/new.html.erb
<div class="access new">
  <h2>Welcome</h2>
  <p>A simulated log in form</p>

  <%= form_tag(access_path) do %>
    <table summary="login">
      <tr>
        <th><%= label_tag(:username) %></th>
        <td><%= text_field_tag(:username, params[:username]) %></td>
      </tr>
      <tr>
        <th><%= label_tag(:password) %></th>
        <td><%= password_field_tag(:password) %></td>
      </tr>
    </table>

    <div class="form-buttons">
      <%= submit_tag("Log In") %>
    </div>

  <% end %>
</div>

app/views/categories/delete.html.erb
<h1>Categories#delete</h1>
<p>Find me in app/views/categories/delete.html.erb</p>

app/views/categories/edit.html.erb
<h1>Categories#edit</h1>
<p>Find me in app/views/categories/edit.html.erb</p>

app/views/categories/index.html.erb
<%= link_to('Back to Menu', menu_path, class: 'back-link') %><br />

<div class="categories index">
  <h2>Categories</h2>

  <%= link_to("Add New Category", new_category_path, class: 'action new') %>

  <table class="listing" summary=" list" style="width: 100%;">
    <tr class="header">
      <th>#</th>
      <th>Category</th>
      <th>Actions</th>
    </tr>
    <% @categories.each do |category| %>
    <tr>
      <td><%= category.id %></td>
      <td><%= category.name %></td>
      <td class="actions">
        <%= link_to("Show", category_path(category), class: 'action show') %>
        <%= link_to("Edit", edit_category_path(category), class: 'action edit') %>
        <%= link_to("Delete", delete_category_path(category), class: 'action delete') %>
      </td>
    </tr>
    <% end %>
  </table>
</div>

app/views/categories/new.html.erb
<h1>Categories#new</h1>
<p>Find me in app/views/categories/new.html.erb</p>

app/views/categories/show.html.erb
<%= link_to("Back to Categories", categories_path, class: 'back-link') %>

<div class="categories show">
  <h2>Show Category</h2>

  <div class="actions">
    <%= link_to('Edit', edit_category_path(@category)) %>
    <%= link_to('Delete', delete_category_path(@category)) %>
  </div>

  <table summary="Category detail view">
    <tr>
      <th>Name</th>
      <td><%= @category.name %></td>
    </tr>
    <tr>
      <th>Categories</th>
      <td>
        <ul>
        <% @category.tasks.each do |task| %>
          <% if task.name %>
            <li><%= link_to(task.name, task_path(task), class: 'action show') %></li>
          <% end %>
        <% end %>
        </ul>
      </td>
    </tr>
    <tr>
      <th>Created</th>
      <td><%= @category.created_at %></td>
    </tr>
    <tr>
      <th>Updated</th>
      <td><%= @category.updated_at %></td>
    </tr>
  </table>

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TaskManager</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/main/about.html.erb
<h2>About</h2>

<p>Description of the Task Manager.</p>
<p>Created by <%= @created_by %></p>

ID: <%= @id %><br />
Page: <%= @page %><br />

app/views/main/index.html.erb
<h1>Task Manager</h1>
<p>This is an application for managing a to do list.</p>

<%= link_to('Categories', categories_path) %><br />
<%= link_to('Tasks', tasks_path(page: 1)) %><br />
<%= link_to('About', {action: 'about', page: 5, id: 20}) %><br />

app/views/tasks/_form.html.erb
<table summary="Task form fields">
  <tr>
    <th>Name</th>
    <td><%= f.text_field(:name) %></td>
  </tr>
  <tr>
    <th>Position</th>
    <td><%= f.text_field(:position) %></td>
  </tr>
  <tr>
    <th>Completed</th>
    <td><%= f.check_box(:completed) %></td>
  </tr>
  <tr>
    <th>Description</th>
    <td><%= f.text_area(:description) %></td>
  </tr>
</table>

app/views/tasks/delete.html.erb
<%= link_to("Back to List", tasks_path, class: 'back-link') %>

<div class="tasks delete">
  <h2>Delete Task</h2>

  <%= form_for(@task, method: 'delete') do |f| %>
    <% # url: task_path(@task), method: 'delete' %>

    <p>Are you sure you want to permanently delete this task?</p>
    <p><%= @task.name %></p>

    <div class="form-buttons">
      <%= f.submit("Delete Task") %>
    </div>

  <% end %>
</div>

app/views/tasks/edit.html.erb
<%= link_to("Back to List", tasks_path, :class => 'back-link') %>

<div class="tasks edit">
  <h2>Edit Task</h2>

  <%= form_for(@task) do |f| %>
    <% # url: task_path(@task), method: 'patch' %>

    <%= render(partial: 'form', locals: {f: f}) %>

    <div class="form-buttons">
      <%= f.submit("Edit Task") %>
    </div>

  <% end %>
</div>

app/views/tasks/index.html.erb
<%= link_to('Back to Menu', menu_path, class: 'back-link') %><br />

<div class="tasks index">
  <h2>Tasks</h2>

  <%= link_to("Add New Task", new_task_path, class: 'action new') %>

  <table class="listing" summary="Task list" style="width: 100%;">
    <tr class="header">
      <th>#</th>
      <th>Task</th>
      <th>Completed</th>
      <th>Category</th>
      <th>Actions</th>
    </tr>
    <% @tasks.each do |task| %>
    <tr>
      <td><%= task.position %></td>
      <td><%= task.name %></td>
      <td><%= task.completed? ? 'Yes' : 'No' %></td>
      <td><%= task.category&.name || '-' %></td>
      <td class="actions">
        <%= link_to("Show", task_path(task), class: 'action show') %>
        <%= link_to("Edit", edit_task_path(task), class: 'action edit') %>
        <%= link_to("Delete", delete_task_path(task), class: 'action delete') %>
      </td>
    </tr>
    <% end %>
  </table>
</div>

app/views/tasks/new.html.erb
<%= link_to("Back to List", tasks_path, :class => 'back-link') %>

<div class="tasks new">
  <h2>Create Task</h2>

  <%= form_for(@task) do |f| %>
    <% # url: tasks_path, method: 'post' %>

    <%= render(partial: 'form', locals: {f: f}) %>

    <div class="form-buttons">
      <%= f.submit("Create Task") %>
    </div>

  <% end %>
</div>

app/views/tasks/show.html.erb
<%= link_to("Back to List", tasks_path, class: 'back-link') %>

<div class="tasks show">
  <h2>Show task</h2>

  <div class="actions">
    <%= link_to('Edit', edit_task_path(@task)) %>
    <%= link_to('Delete', delete_task_path(@task)) %>
  </div>

  <table summary="Task detail view">
    <tr>
      <th>Name</th>
      <td><%= @task.name %></td>
    </tr>
    <tr>
      <th>Position</th>
      <td><%= @task.position %></td>
    </tr>
    <tr>
      <th>Completed</th>
      <td><%= @task.completed? ? 'Yes' : 'No' %></td>
    </tr>
    <tr>
      <th>Description</th>
      <td><%= @task.description %></td>
    </tr>
    <tr>
      <th>Category</th>
      <td>
        <% if @task.category %>
          <%= link_to(@task.category.name, category_path(@task.category), class: 'action show') %>
        <% end %>
      </td>
    </tr>
    <tr>
      <th>Created</th>
      <td><%= @task.created_at %></td>
    </tr>
    <tr>
      <th>Updated</th>
      <td><%= @task.updated_at %></td>
    </tr>
  </table>

</div>